### ISSUE TITLE
About shakespeare dataset

### ISSUE THREAD

**Issue by MirandaHe** [vaseline555/SuPerFed#2]
Thank you for your outstanding work. When I tried to run shakespeare's data set, I encountered the following problems. Do I need to download the data set by myself and construct the required directory path?
<img width="798" alt="image" src="https://github.com/vaseline555/SuPerFed/assets/105597549/42422827-06fd-487c-993b-76c771bc95b5">
Looking forward to your reply

**Comment by vaseline555** [comment]
Hi, thank you for your interest in my work!

Yes, you should prepare _Shakespeare dataset_ manually, according to the instruction described in the original LEAF benchmark repository. Please see: https://github.com/TalwalkarLab/leaf/tree/master/data/shakespeare

Since it is somewhat bothersome, I've recently released another repo (for FL research) that supports automatic preparation of **all datasets** in LEAF benchmark. Please see: https://github.com/vaseline555/Federated-Learning-PyTorch

BTW, I have not yet completed transplanting `SuPerFed` into that repo.
I hope you find this information helpful but if you require any further clarification please let me know.

Thank you.


Best,
Adam

**Comment by MirandaHe** [comment]
Thank you for your answer, which solves some of my confusion. Ok! I'll learn about your new job. Thank you very much! Please forgive me if I'm new to this field。

**Comment by vaseline555** [comment]
No problem at all, and welcome to FL community. 😄
Fingers crossed!
